### ISSUE TITLE
Unexpected values received for types i8 and i16 from ink! contract

### ISSUE THREAD

**Issue by sharma66mahesh** [polkadot-js/api#5483] opened 2023-02-14 16:55 UTC
* **I'm submitting a ...**

  - [x] Bug report

* **What is the current behavior and expected behavior?**
Upon uploading [this ink! contract](https://pastebin.com/z2sehh14), I was expecting to receive the values of the variables `my_i8` and `my_i16` to be `127` and `32767` as it was set in the ink! contract respectively.

However, I received `-129` and `-32769` as the values for `my_i8` and `my_i16` respectively.

The following is the output of querying the contract's `get` method:
```
{"msg":"ICE/SNOW Network","u8Arr":"0x010203","value":"0x7fffffffffffffffffffffffffffffff","isTrue":true,"myAccount":"npRm3oLNUahbPgUnwjPYw9oLWdEigk6aHzwtvj4nibfAJMYVo","myBalance":123123123123,"myHash":"0xe0d83c067d9abf593a8089ef1f21fc30fafb02a8dd67a862f8ca47eb158735b9","myVec":[-65535,-65534,-65533,-65532,-65531,-65530,-65529,-65528,-65527,-65526,-65525],"myStruct":{"id":1,"status":"Invalid","strArr":["Str1","Str2"]},"myIntStruct":{"myU8":255,"myU16":65535,"myU32":4294967295,"myU64":"0xffffffffffffffff","myU128":"0xffffffffffffffffffffffffffffffff","myI8":-129,"myI16":-32769,"myI32":2147483647,"myI64":"0x7fffffffffffffff","myI128":"0x7fffffffffffffffffffffffffffffff"}}
```

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**
  - Version: [polkadot-v0.9.36](https://github.com/paritytech/substrate/tree/polkadot-v0.9.36/frame/contracts), @polkadot-js/api v9.13.6, @polkadot-js/api-contract v9.13.6
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by cmichi** [comment] 2023-02-16 11:11
@statictype @DoubleOTheven Any idea?

**Comment by DoubleOTheven** [comment] 2023-02-20 22:07
Hey @sharma66mahesh, would you please share the metadata for that contract?

I would try updating polkadotjs to the latest version in the mean time

**Comment by sharma66mahesh** [comment] 2023-02-21 05:47
@DoubleOTheven  Here is the link to the compiled contract:
https://easyupload.io/m/ggzozt

**Comment by DoubleOTheven** [comment] 2023-02-21 14:53
@sharma66mahesh Thanks for sharing

1. [I tested on Contracts on Rococo](https://contracts-ui.substrate.io/contract/5F28mgB5QjuRdo9SXXrfPX5kAT3cEbtiQuD3M2zqR3yVLoLk) and it is exactly as you said. 
2. I also tested on a local React app and decoded the raw values. Same result:

```js
{
  "myIntStruct": ​​{
    "myI16": "-32,769"
    "myI8": "-129"
    // ... omitted
​​  }
  // ...omitted
}
```
It looks like `i8` and `i16` values are not correctly decoded from the raw response. `i64` **IS**, however. I will ping the dev team on internal comms.

**Comment by jacogr** [comment] 2023-03-12 18:39
Closing on the back of #5506 which seems like it would be the root cause. Comments to "still an issue on latest" would re-open.

**Comment by statictype** [comment] 2023-03-30 10:07
still an issue on latest

**Comment by jacogr** [comment] 2023-11-18 10:37
https://github.com/polkadot-js/api/issues/5702 addresses the root causes (tracing back to the common repo).

**Closed by jacogr** 2023-11-18 10:37 UTC
