### ISSUE TITLE
Unable to connect + Uncatchable api error

### ISSUE THREAD

**Issue by jak-pan** [polkadot-js/api#1742] opened 2020-01-23 15:50 UTC
I'm trying to connect to my unsynced node with api 1.0.0-beta.17 
```
target=#750431 (25 peers), best: #520014
```
I'm getting 
![Screen Shot 2020-01-23 at 16 42 13](https://user-images.githubusercontent.com/3409250/72999295-74938080-3dff-11ea-9667-bd96dcc9c5bd.png)

which is uncatchable with both of these

```javascript 
try {
  let api = await ApiPromise.create().catch(e => {})
} catch (e) {}
```

It also doesn't emit error on 
```javascript
provider.on('error',(e)=>{})
```

It results in stuck application since I can't react on anything that happened here. It also happens when you get error while connecting to ``wsprovider`` but it can be handled by wrapping api creation inside another promise, which I can reject. It is not ideal, but it works.

When trying to connect to ``wss://cc3-5.kusama.network/`` I get this on the other hand

![Screen Shot 2020-01-23 at 16 41 42](https://user-images.githubusercontent.com/3409250/72999309-79583480-3dff-11ea-839f-8dc55b605d44.png)

**Comment by jacogr** [comment] 2020-01-23 16:08
In this case you got very unlucky on Kusama. The issue is that at some point metadata v9 was actually broken - a type was added without changing the metadata version. (The bump to metadata v10 fixed that - retrospectively)

However, despite the brokenness there, going to keep this issue as logged and see what we can do around the error handling so it properly propagates.

**Comment by jacogr** [comment] 2020-02-14 13:23
@jak-pan With the changes from @laec is this still an issue for you?

**Comment by jak-pan** [comment] 2020-02-15 11:06
This looks like a good fix. It should be documented however to catch apiPromise.create() since it can crash now.

**Comment by jacogr** [comment] 2020-02-15 12:06
Closing, documentation updates logged.

**Closed by jacogr** 2020-02-15 12:06 UTC
Labels: +P3, -size-s, @api, [bug], [enhancement]
