### ISSUE TITLE
api.query.system seem not work

### ISSUE THREAD

**Issue by shangpit** [polkadot-js/api#3066] opened 2021-01-17 09:12 UTC
I write a sample api test, but dont understand why blockhash of a block equal "0x0000....", or may be Node not sync already
./sample.js
```js
const { ApiPromise, WsProvider } = require('@polkadot/api');

const  sample = async () => {
  const wsProvider = new WsProvider('ws://127.0.0.1:9944');
  const api = await ApiPromise.create({ provider: wsProvider });
  const state = await api.query.system.blockHash(2317045);
  return state;
};

module.exports = { sample };
```

./sample.test.js
```js
const {sample} = require('./sample.js')
 describe('Connect with api', () => {
    it('query sample api', async () => {
      const result = await sample();
      expect(result).toEqual(0)
    });
  });
```

Expected: 0
Received: "0x0000000000000000000000000000000000000000000000000000000000000000"

<img width="1792" alt="Screen Shot 2021-01-17 at 4 11 20 PM" src="https://user-images.githubusercontent.com/49492179/104836183-a6d6a180-58de-11eb-958b-042071e938fa.png">

**Comment by shangpit** [comment] 2021-01-17 12:18
My problem is watching for deposit transaction to an address, can you support me? @jacogr 
- What testnet version to test? I used to try https://github.com/paritytech/polkadot-launch, is it ok?
- How can a query txid of deposit transaction, when i used to query with 
```js
await api.query.system.account(ADDR);
```
it's just show the balance, how i can query deposit transaction to ADDR

**Comment by jacogr** [comment] 2021-01-17 12:45
You need to listen for the events. Specifically probably `balances.Transfer` or `balances.deposit`.  See https://polkadot.js.org/docs/substrate/events#balances & https://polkadot.js.org/docs/api/cookbook/blocks#how-do-i-map-extrinsics-to-their-events 

(in the latter example it maps to a block extrinsic, but if you only listen to `system.events()` only the event extraction part is relevant there)

**Comment by shangpit** [comment] 2021-01-18 01:11
Thank you very much about supported! <3. When i want to query
```js
api.query.balances.events
```
There seems can not query event of balance
![Untitled](https://user-images.githubusercontent.com/49492179/104862066-c9130280-5964-11eb-9cb6-d8227dd01c13.png)

**Comment by shangpit** [comment] 2021-01-18 01:45
Your answer and in documentation just talking about system events, not have balances events

**Comment by shangpit** [comment] 2021-01-18 07:15
Unknown error: Client(UnknownBlock("State already discarded for BlockId::Hash(0x4888121987dc75aad124368b38a8f6b7f4ea8cbe19a982e0c0ae56c3f9dedce8)"))

```js
const blockHash = await api.rpc.chain.getBlockHash(3390096);
const allEvent = await api.query.system.events.at(blockHash);
```

seems error when node is sync up

**Comment by jacogr** [comment] 2021-01-18 08:38
The system events contains all events raised. So the balances will be in there.

Substrate runs with default 256 block state pruning. If you wish to query older blocks, you need to run the RPC node in archive mode.

**Comment by shangpit** [comment] 2021-01-19 09:59
Thank you very much for your support!

```js
const lastHdr = await api.rpc.chain.getHeader();
const startHdr = await api.rpc.chain.getBlockHash(lastHdr.number.unwrap().subn(500));

// retrieve the range of changes
const changes = await api.query.system.account.range([startHdr]);

changes.forEach(([hash, value]) => {
  console.log(hash.toHex(), value.toHuman());
});
```

this example come with error 
```js
Account is a Map and requires one argument
```

**Comment by jacogr** [comment] 2021-01-19 10:13
I would not suggest using `.range` at all - the reason is that while the API has it decorated, the RPCs that are used to effect this are behind the `--unsafe` flag now on Substrate. So for instance on chains such as Kusama & Polkadot it is not exposed. So while it will work locally, unless you provide your own RPC node, it is unlikely to be available.

So with the above in mind, this is why we have this in the definitions - https://github.com/polkadot-js/api/blob/master/packages/api/src/types/storage.ts#L51-L52 (It is due for removal sinec it basically has no support anymore on RPC nodes)

To answer the query: Any map type of double map needs the account, so as per the definitions above you need to pass the account and the second argument, i.e. the ss58 address would work. (So you can do a range query on a specific item only)

**Comment by shangpit** [comment] 2021-01-19 10:22
:( This is a effectly way to get the hash of block that change balance of account instead of query each block to get exintrics infomation

**Comment by jacogr** [comment] 2021-01-19 10:27
Yes, agreed. The issue is that it is easy to DOS the node - hence the addition of hiding this behind the `--unsafe` flag on Substrate.

**Comment by shangpit** [comment] 2021-01-19 10:29
In a market place, it require to trace deposit in to a ```Map of Address```, do you have experience in query ```balances.Transfer event``` in a map of address, or in a range of block?

**Comment by jacogr** [comment] 2021-01-19 10:34
Listen to `system.events` and extract the `balances.Transfer` events, for instance -

```js
api.query.system.events(({ phase, event }) => {
  if (phase.isApplyExtrinsic) {
    if (api.events.balances.Transfer.is(event)) {
      const [from, to, value] = event.data;
      const isMine = MY_LIST.find((a) => to.eq(a));
      
      if (isMine) {
        console.log(to.toString(), 'received', value.toHuman());
      }
    }
  }
});
```

**Comment by jacogr** [comment] 2021-01-26 13:09
Closing.

**Closed by jacogr** 2021-01-26 13:09 UTC
Labels: <support>
