### ISSUE TITLE
no error throw when sender has no enough balance to transfer

### ISSUE THREAD

**Issue by PercivalZhang** [polkadot-js/api#1484] opened 2019-10-14 11:51 UTC
when call extrinsic, api will hang there and no errors will be thrown when sender has no enough balance. there used to throw invalid extrinsic when the same situation

**Comment by jacogr** [comment] 2019-10-14 13:12
This is a core substrate issue, introduced here as part of the PR - https://github.com/paritytech/substrate/pull/3650

Basically the transaction pool is now async, however the initial failures are not bubbled via RPC. (You can verify by checking the network traffic, the error is not sent over RPC)

**Comment by jacogr** [comment] 2019-10-14 15:00
Fix for Substrate master - https://github.com/paritytech/substrate/pull/3817

**Comment by jacogr** [comment] 2019-10-14 15:42
Marked "unconfirmed" & "bug" - since it is not an actual API issue. (However the fix may have some impacts since the has been rework, so testing required with the fixed version)

**Comment by PercivalZhang** [comment] 2019-10-15 01:46
thank you for quick response and wait for the fixing ready

**Comment by jacogr** [comment] 2019-10-15 08:42
The above PR seems to do the trick, actual raw outputs -

```
2019-10-15 10:41:49          API-WS: calling author_submitAndWatchExtrinsic {"id":10,"jsonrpc":"2.0","method":"author_submitAndWatchExtrinsic","params":["0x350283ff0c9f6509b840bea296f9e75a9c730be8b07c4ba6b1d4449e991c97c2b158ad4e00a167c64820acc31551c49f2425aa914b137a351bb11e558f995777e40f774b1b8a3636c15a0b06004dff3d570792a2d31804cef33820af76471f1341421f0c850100000600ff8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a483a85f102"]}
2019-10-15 10:41:49          API-WS: received {"jsonrpc":"2.0","error":{"code":1010,"message":"Invalid Transaction","data":"Payment"},"id":10}
2019-10-15 10:41:49        RPC-CORE: submitAndWatchExtrinsic (extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Payment
```

**Comment by jacogr** [comment] 2019-10-15 09:29
Merged on substrate.

**Closed by jacogr** 2019-10-15 09:29 UTC
Labels: <substrate>, [bug]
