### ISSUE TITLE
Getting the SignerPayload back based on the raw data

### ISSUE THREAD

**Issue by aserafin** [polkadot-js/api#4995] opened 2022-06-30 11:05 UTC
Hi, 

I'm creating a `SignerPayload` with the following code, calling `toRaw()` on it and send the data to some other process. 

```
const payload = api.createType('SignerPayload', {
          method: transaction,
          nonce,
          genesisHash: api.genesisHash,
          blockHash: api.genesisHash,
          runtimeVersion: api.runtimeVersion,
          version: api.extrinsicVersion,
});

const raw = payload.toRaw();
```

I'm wondering if there's some way to convert the raw representation back to the `SignerPayload` object?

**Comment by jacogr** [comment] 2022-07-01 16:41
With toPayload, yes. With toRaw, no. 

The issue is that the extrinsic is without length prefix, so it is basically “impossible “ to decode. (It can be done, on the Ledger they parse from the last bytes to the first bytes, in reverse)

With the above in mind “no” (and won’t be supported)

**Comment by jacogr** [comment] 2022-07-06 17:44
Closing, answered.

**Closed by jacogr** 2022-07-06 17:44 UTC
Labels: <support>
