### ISSUE TITLE
Cannot find module bs58 with version 0.81.1

### ISSUE THREAD

**Issue by kushptlapigarage** [polkadot-js/api#1058] opened 2019-06-26 16:23 UTC
Seeing `Error: Cannot find module 'bs58'` with @polkadot/api version *^0.81.1* ( believe it's latest )

*Reproduction*
```
$ node -v
v11.6.0
$ yarn -v
1.13.0
$ uname -a
Darwin MacBook-Pro 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
$ cat package.json 
{
  "name": "polkadot-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@polkadot/api": "^0.81.1"
  }
}
$ cat index.js
const { ApiPromise } = require("@polkadot/api");
```
Then run command
```
$ node index.js
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'bs58'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/zadkiel/Code/polkadot-test/node_modules/@polkadot/util-crypto/address/decode.js:10:34)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)```

**Comment by amaurymartiny** [comment] 2019-06-26 16:25
Duplicate of https://github.com/polkadot-js/api/issues/1026, please see that thread for a solution.

**Closed by amaurymartiny** 2019-06-26 16:25 UTC
