### ISSUE TITLE
Empty tuple is encoded as null

### ISSUE THREAD

**Issue by Diiaablo95** [polkadot-js/api#4146] opened 2021-11-02 10:01 UTC
After upgrading our parachain to use metadata v14, we now have no way to distinguish whether an element is present or not in a `StorageMap<AccountId32 ()>`, as the `api.query.pallet.storage(key)` returns `null` in both cases. I can see also from polkadotjs apps that the map is a map from `AccountId32` to `Option<Null>`.
So far, the only workaround I found is to fetch ALL the keys via `api.query.pallet.keys` and then filter, but that can get quite expensive if the map has a lot of keys. Is there a more efficient way to check for existence in such a map or, if there is not, would it be possible to fix this issue by encoding empty tuples differently? I am not sure if this issue pertains the SDK side or the chain side.

I also opened an [issue in the scale-info repo](https://github.com/paritytech/scale-info/issues/134).

**Comment by jacogr** [comment] 2021-11-02 11:18
The API will, when the storage key from the node returns `null` apply the fallback as specified in the metadata. The fallback is generally the `Default` value.

So yes, it is intentional, and by design with the fallback.

`()` has the same encoding as `Null` on the JS side (empty bytes).

**Comment by Diiaablo95** [comment] 2021-11-02 11:52
Ok so there is no efficient way to understand whether a key exists in a given map or not?

**Comment by Diiaablo95** [comment] 2021-11-04 09:16
Ok I have found a workaround using raw keys that avoids the automatic encoding of `()` to `Null`.

```typescript
  // Compute the raw key for the given storage element
  const rawKey = await api.query.pallet.storage.key(input)
  // Fetch the raw storage entry using the computed key
  const encodedStorageValue = await api.rpc.state.queryStorageAt<Codec[]>([rawKey])
  // Checks the retrieved encoding to check whether the value is actually present or not
  const isPresent = encodedStorageValue.pop()!.toU8a()[0] === 1
```

It might not be very beautiful, but it does what it needs to do without requiring to fetch the whole storage content and then filtering afterwards. I am still open to suggestions to make this better, but I also think this might help other people in the same situation.

**Comment by jacogr** [comment] 2021-11-08 14:33
Closing.

**Closed by jacogr** 2021-11-08 14:33 UTC
Labels: <support>
