### ISSUE TITLE
`Unable to decode storage society.candidates` when there's a vouch in the candidates list

### ISSUE THREAD

**Issue by laurogripa** [polkadot-js/api#5795] opened 2024-02-21 08:39 UTC
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Similarly to #5766, society.candidates is failing after the pallet was updated to V2. It works normally most of the time, but breaks if there's a candidate in the list that was accepted through vouching.

The error can be reproduced in simple steps:
- Use chopsticks and add a candidate with vouch to the storage;
- Connect PolkadotJS apps to chopsticks;
- Call society.candidates in the chain state UI. 

```
2024-02-21 05:27:51        RPC-CORE: queryStorageAt(keys: Vec<StorageKey>, at?: BlockHash): Vec<StorageChangeSet>:: Unable to decode storage society.candidates: entry 7:: createType(PalletSocietyCandidacy):: decodeU8aStruct: failed at 0xd83d00000000000000000000… on kind (index 2/5): {"_enum":{"Deposit":"u128","Vouch":"(AccountId32,u128)"}}:: Unable to create Enum via index 216, in Deposit, Vouch
```

![image](https://github.com/polkadot-js/api/assets/6154932/27fe4113-21ec-4402-9d47-0a9c2008006f)

**Environment**

  - Version: v10.11.2 (latest)
  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (5.3.3)
    - [ ] Other

**Comment by TarikGul** [comment] 2024-03-07 14:00
I checked the `society.candidates` usage in the UI with Kusama, and with the API and found no issues. If this is a chopsticks issue it's out of scope for this repo. Closing as I can't reproduce with a base chain.

**Closed by TarikGul** 2024-03-07 14:00 UTC

**Comment by laurogripa** [comment] 2024-03-08 07:49
> I checked the `society.candidates` usage in the UI with Kusama, and with the API and found no issues. If this is a chopsticks issue it's out of scope for this repo. Closing as I can't reproduce with a base chain.

I can open an issue on Chopsticks as well, but I'm inclined to think it's a problem in the API. Keep in mind that it only happens when one of the candidates was accepted through a `vouch`. If the list contains only normal candidates, the issue doesn't happen.

**Comment by laurogripa** [comment] 2024-03-08 07:51
> I checked the `society.candidates` usage in the UI with Kusama, and with the API and found no issues. If this is a chopsticks issue it's out of scope for this repo. Closing as I can't reproduce with a base chain.

@TarikGul, thank you for your attention. I can open an issue on the Chopsticks repo as well, but I'm inclined to think it's a problem on the API. Keep in mind that it only happens when one of the candidates was accepted through a `vouch`. If the list contains only normal candidates, the issue doesn't happen.

**Comment by TarikGul** [comment] 2024-03-08 13:41
<img width="1717" alt="Screenshot 2024-03-08 at 8 40 37 AM" src="https://github.com/polkadot-js/api/assets/47201679/58639a65-ebb9-45fc-9d56-01c07f4b7cda">


So I just checked with Chopsticks again. The version used in the UI was updated, and it worked with `society.candidates`. It might have just needed a bump in the API.
