### ISSUE TITLE
When catches events, happened error.

### ISSUE THREAD

**Issue by satellitex** [polkadot-js/api#970] opened 2019-06-05 07:32 UTC
polkadot-js version is 0.79.1

When I try a sample code.
https://polkadot.js.org/api/examples/promise/08_system_events/

I happened error below.
```
Unable to decode Uint8Array for type 'Phase': Unable to create Enum via index 4, in ApplyExtrinsic, Finalization
Unable to decode Uint8Array for type 'EventRecord': Unable to create Enum via index 4, in ApplyExtrinsic, Finalization
Unable to decode Uint8Array for type 'EventRecord': Unable to create Enum via index 4, in ApplyExtrinsic, Finalization
Unable to decode Uint8Array for type 'EventRecord': Unable to create Enum via index 4, in ApplyExtrinsic, Finalization
Unable to decode Uint8Array for type 'Phase': Unable to create Enum via index 42, in ApplyExtrinsic, Finalization
Unable to decode Uint8Array for type 'EventRecord_0_76': Unable to create Enum via index 42, in ApplyExtrinsic, Finalization
Unable to decode Uint8Array for type 'EventRecord_0_76': Unable to create Enum via index 42, in ApplyExtrinsic, Finalization
Unable to decode Uint8Array for type 'EventRecord_0_76': Unable to create Enum via index 42, in ApplyExtrinsic, Finalization
Unable to decode storage system.events: Unable to create Enum via index 42, in ApplyExtrinsic, Finalization
2019-06-05 16:19:00        RPC-CORE: subscribeStorage (keys: Vec<StorageKey>): StorageChangeSet:: Unable to create Enum via index 42, in ApplyExtrinsic, Finalization
```

**Comment by jacogr** [comment] 2019-06-05 07:49
Could you please upgrade to 0.80.1 

These issues are generally caused by the node version being ahead in terms of metadata support.

The same code, with the latest API running - https://polkadot.js.org/apps/#/js/share/vAVgYXBpLnF1ZXJ5LnN5c3RlbS5ldmVudHMoKAkIkCkgPT4gewogICAgY29uc29sZS5sb2coYFxuUmVjZWl2ZWQgJHsJKyAubGVuZ3RofSAJDxA6YCk7CgU5kC8vIGxvb3AgdGhyb3VnaCB0aGUgVmVjPEV2ZW50UmVjb3JkPgoBYgk5LC5mb3JFYWNoKChyZQEcBCkgFYMAIAFMGGV4dHJhY3QFRxRwaGFzZSwJOQwgYW5kBRUFRxQgdHlwZXMFgAm7CHQgewkaACwJNhAgfSA9IAliADsyJwAFOQQgPQktAC4BDghEZWYNywAgAYFkc2hvdyB3aGF0IHdlIGFyZSBidXN5IHdpdGgdSDkqAHQtISQuc2VjdGlvbn06ERFIbWV0aG9kfTo6IChwaGFzZT0kewUIMC50b1N0cmluZygpfSkhRyEdCcYdVxlZNG1ldGEuZG9jdW1lbnRhAWQALh1CAUENQj6KARhlYWNoIG9mJTZUcGFyYW1ldGVycywgZGlzcGxheWluZwUbIQQlXgxkYXRhDUslZQAuARE5sAEOGCwgaW5kZXgytQFKuwABvQFXBHNbBS8AXSVoEH06ICR7AUU+vwApAEB9KTsKICAgIH0pOwogIH0pOw==

**Comment by satellitex** [comment] 2019-06-05 08:32
@jacogr Thank you!
But, I have a error yet.
I execute my substrate project node on substrate v1.0.0rc2.

```
Unable to decode Uint8Array for type 'Phase': Unable to create Enum via index 4, in ApplyExtrinsic, Finalization
Unable to decode Uint8Array for type 'EventRecord': Unable to create Enum via index 4, in ApplyExtrinsic, Finalization
Unable to decode Uint8Array for type 'EventRecord': Unable to create Enum via index 4, in ApplyExtrinsic, Finalization
Unable to decode Uint8Array for type 'EventRecord': Unable to create Enum via index 4, in ApplyExtrinsic, Finalization
Unable to decode Uint8Array for type 'Phase': Unable to create Enum via index 9, in ApplyExtrinsic, Finalization
Unable to decode Uint8Array for type 'EventRecord_0_76': Unable to create Enum via index 9, in ApplyExtrinsic, Finalization
Unable to decode Uint8Array for type 'EventRecord_0_76': Unable to create Enum via index 9, in ApplyExtrinsic, Finalization
Unable to decode Uint8Array for type 'EventRecord_0_76': Unable to create Enum via index 9, in ApplyExtrinsic, Finalization
Unable to decode storage system.events: Unable to create Enum via index 9, in ApplyExtrinsic, Finalization
2019-06-05 17:29:40        RPC-CORE: subscribeStorage (keys: Vec<StorageKey>): StorageChangeSet:: Unable to create Enum via index 9, in ApplyExtrinsic, Finalization
```

**Comment by jacogr** [comment] 2019-06-05 08:35
Node template or the substrate v1.0 branch?

(I've tested against both Alexander, which is based on Substrate 1.0 and substrate master)

**Comment by satellitex** [comment] 2019-06-06 06:33
@jacogr 
I still get errors. And sorry, I don't say information. 

I run two nodes simultaneously.
### substrate node A
`./target/debug/a --base-path /tmp/a --port 30333 --ws-port 9944 --dev`
### substrate node B
`./target/debug/b --base-path /tmp/b --port 30334 --ws-port 9955 --dev`

I listen to events from both by using ApiPromise.
`const nodeA = await ApiPromise.create({  provider: new WsProvider(ws://127.0.0.1:9944)`
`const nodeB = await ApiPromise.create({  provider: new WsProvider(ws://127.0.0.1:9955)`

**Comment by jacogr** [comment] 2019-06-06 07:06
What happens when you run 1 Node? Are both binaries the the same version with the same Metadata?

**Comment by satellitex** [comment] 2019-06-06 07:25
> What happens when you run 1 Node?
I get error too when 1 Node issue to events.
```
Unable to decode Uint8Array for type 'Phase': Unable to create Enum via index 4, in ApplyExtrinsic, Finalization
Unable to decode Uint8Array for type 'EventRecord': Unable to create Enum via index 4, in ApplyExtrinsic, Finalization
Unable to decode Uint8Array for type 'EventRecord': Unable to create Enum via index 4, in ApplyExtrinsic, Finalization
Unable to decode Uint8Array for type 'EventRecord': Unable to create Enum via index 4, in ApplyExtrinsic, Finalization
```
But after that, I was able to get the intended event when 1 node.
1 node case, `RPC-CORE: subscribeStorage (keys: Vec<StorageKey>): StorageChangeSet:: Unable to create Enum via index 9, in ApplyExtrinsic, Finalization` error is not found.

> Are both binaries the the same version with the same Metadata?
No. Specifically, I use these two nodes.
https://github.com/stakedtechnologies/Plasm/blob/fix-divide-plasm-nodes/child/src/main.rs
https://github.com/stakedtechnologies/Plasm/blob/fix-divide-plasm-nodes/src/main.rs

**Comment by jacogr** [comment] 2019-06-06 07:39
Ok, so these are custom nodes, substrate master. Which means that the metadata exposed does not contain all the information required, i.e. In the Phase, there are extra event types, not just these - https://github.com/paritytech/substrate/blob/9687db56516ef573f650dadc030315b78d708cc4/srml/system/src/lib.rs#L210

The issue with those are that they are not exposed by the runtime metadata, so you would need to provide your own overrides for the Phase type.

**Comment by satellitex** [comment] 2019-06-06 09:34
@jacogr thanks!
How do I override Phase type on SubstrateNode or js codes?

**Comment by jacogr** [comment] 2019-06-06 14:06
Could you point me to where you made changes to the events?

**Comment by satellitex** [comment] 2019-06-06 15:08
@jacogr 
Substrate codes are
https://github.com/stakedtechnologies/Plasm/blob/fix-divide-plasm-nodes/core/parent/src/mvp.rs#L350

And, js codes are
https://github.com/stakedtechnologies/plasm-client/blob/master/packages/operator/lib/ChainManager.js#L27

**Comment by jacogr** [comment] 2019-06-06 15:47
I don't see that you actually expose the events here - https://github.com/stakedtechnologies/Plasm/blob/fix-divide-plasm-nodes/runtime/src/lib.rs#L224

So they probably are not making it into metadata. Compare with consensus where they are exposed.

**Comment by satellitex** [comment] 2019-06-07 05:42
I think that `construct_runtime!` automaticaly exposes `Module, Call, Storage, Event<T>, Config<T>
 ` if it doesn't specify any types.
Said by https://docs.substrate.dev/docs/construct_runtime#section-no-types-or-default-

**Comment by jacogr** [comment] 2019-06-07 05:45
Do a query for the metadata (can do it via polkadot.js.org/apps -> toolbox -> rpc -> state.getMetadata - it displays the parsed result) and ensure it is in there. (You can just paste the whole JSON result here as well)

Everything in the API is dynamic as the runtime metadata tells it - if the data is not there, it doesn't know what to do.

**Comment by satellitex** [comment] 2019-06-07 05:52
I can get metadata JSON.
https://gist.github.com/satellitex/b11b1de8c95b059a98897fd9bb7a9b06

Are Exposed events this?
https://gist.github.com/satellitex/b11b1de8c95b059a98897fd9bb7a9b06#file-plasm_parent_metadata-json-L891

**Comment by jacogr** [comment] 2019-06-07 06:11
Yes, those are the events. It looks sane, so def. not the cause - they are visible. 

Ok, so next would be to look through all the Rust changes made to anything resembling events & EventRecord and see where extra data sneaks in. The serialization as to what it expects in the records () with the data derived from the metadata and the actual does not match.

It is possible to grab the raw hex value as comes through? (you can run with `NODE_ENV=test node my-tests.scrip.js` and it should log the JSON in/out). So can use this for parsing manually to try and see where the discrepancy lies)

**Comment by satyamakgec** [comment] 2019-06-10 04:36
@jacogr I am also getting these type errors/warnings 
```
Unable to decode Uint8Array for type 'Event': Unable to decode event for index 0x2500
Unable to decode Uint8Array for type 'Phase': Unable to decode event for index 0x2500
Unable to decode Uint8Array for type 'EventRecord': Unable to decode event for index 0x2500
Unable to decode Uint8Array for type 'EventRecord': Unable to decode event for index 0x2500
Unable to decode Uint8Array for type 'EventRecord': Unable to decode event for index 0x2500
```

I am running Substrate from the `node-template` & using the `@polkadot/api v0.79.1`
Here is my script to filter the events - 
https://gist.github.com/satyamakgec/943600c7b86679b44e29d1f4e47712d4

This behavior occurs on some random blocks. I am trying to fetch the events of a particular SRML module between two given block numbers. When my script prints the events on the console these error /warnings also get printed.   

Any specific reason for those errors/warnings. I do not think that this is the error because of the visibility of the events.

**Comment by jacogr** [comment] 2019-06-10 06:30
It basically says - I cannot find event 00 (first) is module 25 (order based on numbers). First try would be to upgrade the API to latest (0.81.1), it always tracks latest substrate master changes. 

Additionally, same would apply as mentioned above - it would be good to dumpy the metadata as a gist and provide the actual raw hex that comes from the node (explained above). Worst case can try manual decoding and see where it breaks down based on the info provided by metadata.

**Comment by satyamakgec** [comment] 2019-06-10 12:50
Thanks @jacogr for the prompt response. I tried after bumping the version of the api but nothing changes.

This is the metadata gist https://gist.github.com/satyamakgec/b9c3a9741bcc6915256dd571581cd4fa
and this is the raw data I got at which I am receiving the error/warnings
```
response = { jsonrpc: '2.0',
  result: '0x100000000000000000010000000000000200000002028eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27dfa0000000000000000000000000000000000000000000000000000000000000000020000000000',
  id: 24 }
``` 
Now I want to figure out the encoded parameter values type so I can decode the raw value. Could you please shred some light here.

**Comment by jacogr** [comment] 2019-06-11 09:37
Thanks a million, Will decode manually and report back. Bit of black magic there - basically, it takes the EventRecord structure and then using the data supplied by the metadata as to the different event types, decodes it.

**Comment by jacogr** [comment] 2019-06-11 10:25
Decoded -

```
10 // length, compact encoded 1 (0x10 >> 2 = 4)

// first
00 // ApplyExtrinsic
00000000 // extrinsic 0
0000 // system.ExtrinsicSuccess

// second
00 // ApplyExtrinsic
01000000 // extrinsic 1
0000 // system.ExtrinsicSuccess

// third
00 // ApplyExtrinsic
02000000 // extrinsic 2
0202 // balances.Transfer
8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48 // addr1
d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d // addr2
fa000000000000000000000000000000 // balance
00000000000000000000000000000000 // balance

// fourth
00 // ApplyExtrinsic
02000000 // extrinsic 2
0000 // system.ExtrinsicSuccess
```

The only funny here is that it uses the old EventRecord structure. So it will show it fails using EventRecord and then passes via EventRecord_0_76 - and return the above results via the callback

**Comment by satyamakgec** [comment] 2019-06-11 12:24
> The only funny here is that it uses the old EventRecord structure. So it will show it fails using EventRecord and then passes via EventRecord_0_76 - and return the above results via the callback

A bit of confusion here please correct me If I am wrong. To decode the raw data you use the old EventRecord structure instead of the new one. During the conversion of raw data into the string, API first tries with new EventRecord structure that attempt gets failed and show `those errors` while api again tries to decode the value with old EventRecord and get passed.   
Or you are talking differently. Either way, how do I get to know the cause of the error?

Thanks a lot for helping me out.

**Comment by jacogr** [comment] 2019-06-11 14:05
So, yes, it will try both new and old as a fallback - so while logging, the errors are innocent. The results will come back from the version that succeeded. If you get errors on both `EventRecord` and `EventRecord_0_76` (76 is the version where introduced), there is foul play. 

(The current new-style EventRecord interface has event topics attached, which was not present in the old version)

**Comment by jacogr** [comment] 2019-06-13 13:38
- Pulled Plasm, built.
- Pulled plasm-ui, installed, copied env
- adjusted `.env` to connect to both `9944` & `9955`
- started nodes with
  - `./plasm-node --base-path /tmp/a --port 30333 --ws-port 9944 --dev`
  - `./plasm-node --base-path /tmp/b --port 30334 --ws-port 9955 --dev`
- started ui via `cd packages/operator && yarn start`

No issues. Closing until reproducable.

**Closed by jacogr** 2019-06-13 13:38 UTC
Labels: <question>

**Comment by satyamakgec** [comment] 2019-06-14 05:45
What does Plasm mean here? Where I can find it? & How it can help me to resolve that issue.

**Comment by jacogr** [comment] 2019-06-14 05:57
@satyamakgec Not sure what you mean. If you look at the person who logged the issue, his implementation (based on Substrate) is Plasm. So trying to download and compile that code was my way of trying to reproduce the specific issue as logged.

For 0.82 (due for release in the next 24 hours), the innocent warning won't be printed anymore, i.e you won't notice when it uses a fallback for an old version of the node. (It will only log when it really can't do anything and completely fails)

**Comment by satyamakgec** [comment] 2019-06-14 10:02
@jacogr Gotcha! I was thinking Plasm is used to resolve the issue :). Anyway thanks a lot to help me out.

**Comment by jacogr** [comment] 2019-06-14 10:17
@satyamakgec Upgrade to 0.81 (release a bit earlier today) and it should be less noisy for you now.
