### ISSUE TITLE
Question about proper usage of the "update" method in Signers (v 5.1.1)

### ISSUE THREAD

**Issue by monitz87** [polkadot-js/api#4559] opened 2022-02-11 20:55 UTC
I'm playing around with custom signers, and implemented this:

```typescript
/**
 * Manages signing payloads with a set of pre-loaded accounts in a Keyring
 */
class KeyringSigner implements PolkadotSigner {
  private currentId = 0;
  private registry = new TypeRegistry();

  /**
   * @hidden
   */
  constructor(public readonly keyring: Keyring) {}

  /**
   * Sign a payload
   */
  public async signPayload(payload: SignerPayloadJSON): Promise<SignerResult> {
    const { keyring, registry } = this;
    const pair = keyring.getPair(payload.address);

    if (!pair) {
      throw new Error('The signer cannot sign transactions for the calling Account');
    }

    registry.setSignedExtensions(payload.signedExtensions);

    const signablePayload = registry.createType('ExtrinsicPayload', payload, {
      version: payload.version,
    });
    const { signature } = signablePayload.sign(pair);

    this.currentId += 1;

    console.log('SIGNATURE', signature);
    console.log('ID', this.currentId);

    return {
      signature,
      id: this.currentId,
    };
  }

  /**
   * @hidden
   */
  public update(id: number, receipt: ISubmittableResult | H256) {
    console.log('TX ID:', id);
    console.log('STATUS', receipt.toHuman());
    throw new Error("YOU WON'T SILENCE ME");
  }
}
```

As you can see, this is not very different from the `SingleAccountSigner` in `packages/api/src/test/util/SingleAccountSigner.ts`, and it works for the most part. The thing is that the `update` method is never called. The logs in `signPayload` appear just fine when signing stuff, but the ones in `update` are never triggered nor is the error thrown. Am I doing something wrong?

Thanks in advance

P.S.: I have two more miscellaneous questions:
1) What determines whether `update` receives a `SubmittableResult` or a `H256`?
2) When should we use `signRaw` instead of `signPayload`?

**Comment by jacogr** [comment] 2022-02-12 07:37
If the update doesn't work, something is wrong, it should update - https://github.com/polkadot-js/api/blob/master/packages/api/src/submittable/createClass.ts#L282

1. if you use the non-subscription form, you get a `Hash`, otherwise the same status as you would receive in a subscription
2. `signRaw` is only meant for signing bytes, i.e. raw messages. The `signPayload` is for transaction signing.

**Comment by monitz87** [comment] 2022-02-12 11:42
Be mindful that I'm using version 5.1.1

Could it be that this was a bug that was fixed in a later version?

Thanks for your other answers

**Comment by jacogr** [comment] 2022-02-12 11:53
I honestly can't say. :( I certainly cannot recall such a bug, I believe that stuff is rather old. 

In the `Hash` version it really _should_ always update, in the subscription version it could be that the `tap` there doesn't quite do what it is supposed to, but it also _looks_ above-board. So cannot spot a bug, but if confirmed broken in a recent version, will certainly attempt to see what and why. The logic is simple there, construct something and pass it along.

**Comment by monitz87** [comment] 2022-02-12 13:07
I'll test on a newer version and let you know. Fwiw, I'm testing with subscription

**Comment by monitz87** [comment] 2022-02-12 17:56
Ok, threw a bunch of logs around and `updateId` is always -1 inside `updateSigner` and `observeSubscribe`, even though `signViaSigner` is returning the id properly. It would seem that `observeSign` isn't passing the `updateId` properly. I'm not familiar with rxjs so my ability to properly debug this is impaired

**Comment by phatNfqAsia** [comment] 2022-02-23 09:27
@monitz87 can you share how you create a transaction then sign it. I am getting the problem 'Invalid Transaction: Transaction has a bad signature' when debugging it when using a SignerPayloadJSON to attach signature to transaction
```typescript
async function main() {
  const wsProvider = new WsProvider("ws://127.0.0.1:9944");
  const api = await ApiPromise.create({
    provider: wsProvider,
  });
  // Create a keyring instance
  const keyring = new Keyring({
    type: "sr25519",
  });

  // Some mnemonic phrase
  const CALVARY_PHRASE = "x x x x x";
  const COOLCORE_ADDR = "15AgbRTVeEPo9jPt168CBXXjJhF1ABgfunz5eRSyv6xyq7SR";
  const priPair = keyring.addFromUri(CALVARY_PHRASE);

  const monitzSigner = new MonitzSigner(keyring);
  const tx = await api.tx.balances.transfer(COOLCORE_ADDR, 12);

  const header = await api.rpc.chain.getHeader();
  const { nonce } = await api.query.system.account(priPair.address);
  const signPayloadJson: SignerPayloadJSON = {
    address: priPair.address,
    blockHash: header.hash.toString(),
    era: tx.era.toHex(),
    genesisHash: api.genesisHash.toString(),
    method: tx.method.toHex(),
    nonce: nonce.toHex(),
    specVersion: api.runtimeVersion.specVersion.toString(),
    blockNumber: header.number.toString(),
    tip: '0x00',
    transactionVersion: api.runtimeVersion.transactionVersion.toString(),
    signedExtensions: [],
    version: EXTRINSIC_VERSION,
  }
  console.log("🚀 ~ file: index.ts ~ line 109 ~ main ~ signPayloadJson", signPayloadJson)
  const { signature } = await monitzSigner.signPayload(signPayloadJson);
  tx.addSignature(keyring.pairs[0].address, signature, signPayloadJson);
  await tx.send();
}

main().then(() => console.log("finished"));
```

**Comment by monitz87** [comment] 2022-02-23 21:20
You should be able to do

```typescript
const tx = await api.tx.balances.transfer(COOLCORE_ADDR, 12);

const signedTx = await tx.signAsync(priPair.address, { nonce, signer: monitzSigner });
await signedTx.send();
```

May I ask why you're trying to sign using my custom signer when you have access to the mnemonic? I ask because you could just do `await tx.signAndSend(priPair, { nonce })` and just forget about the signer

**Comment by coolcorexix** [comment] 2022-02-26 17:06
> If the update doesn't work, something is wrong, it should update as part of the send process - https://github.com/polkadot-js/api/blob/master/packages/api/src/submittable/createClass.ts#L282
> 
> 1. if you use the non-subscription form i.e. `const hash = await tx.signAndSend(account)`, you get a `Hash`, otherwise the same status as you would receive in a subscription when using the `const unsub = await tx.signAndSend(account, () => ...)` (I linked the subscribe logic above, a couple of lines up is the await-hash form)
> 2. `signRaw` is only meant for signing bytes, i.e. raw messages. The `signPayload` is for transaction signing. (Technically you could use `signRaw` for signing transactions as well, some implementation such as that in the extension makes it unusable for tx signing, i.e. it actively prevents it by wrapping the data in the extension itself - however when only the raw form is available, the API will attempt to also use it for tx signing)

As I found out, the bug is due to updateId is passed as a static reference (the value is only fetched once when running at first time). To fix this, just simply add a getter for updateId and call it every you need to access its value.

**Comment by coolcorexix** [comment] 2022-02-27 04:23
> You should be able to do
> ...
@monitz87 from my finding, the extrinsic will be subscribed only if you register the custom signer to the api. Like this:
```
...
  const monitzSigner = new MonitzSigner(keyring);
  api.setSigner(monitzSigner);
  const { nonce } = await api.query.system.account(priPair.address);
  const tx = api.tx.balances.transfer(ADDR, 10);
  await tx.signAndSend(priPair.address, { nonce });
```

**Comment by jacogr** [comment] 2022-02-27 08:25
Closed in https://github.com/polkadot-js/api/pull/4608

**Closed by jacogr** 2022-02-27 08:25 UTC
Labels: [bug], @api, -size-s

**Comment by monitz87** [comment] 2022-02-27 17:24
> @monitz87 from my finding, the extrinsic will be subscribed only if you register the custom signer to the api. Like this:

What do you mean by subscribed? Also, why the distinction?

**Comment by coolcorexix** [comment] 2022-02-28 02:59
> > @monitz87 from my finding, the extrinsic will be subscribed only if you register the custom signer to the api. Like this:
> 
> What do you mean by subscribed? Also, why the distinction?
"subscribed" mean listen to the what happened to the extrinsic on the network (via the api) 
About the distinction, as I inspect the code (see the: https://github.com/polkadot-js/api/blob/master/packages/api/src/submittable/createClass.ts#L282), `this.#updateSigner` is used with params passed from the injected `api`. So when you explicitly set a different signer when signing extrinsic, it is simply not connected to this module I am talking above.

**Comment by monitz87** [comment] 2022-02-28 13:34
Wouldn't it make sense to fix that as well to use `const signer = options.signer || api.signer`?

**Comment by phatNfqAsia** [comment] 2022-03-01 03:13
> Wouldn't it make sense to fix that as well to use `const signer = options.signer || api.signer?`

@monitz87 it might work but I dont know if it match the intent of author. cc @jacogr , thought on this

**Comment by jacogr** [comment] 2022-03-01 07:27
There to be an oversight here - https://github.com/polkadot-js/api/blob/edb06d971a2b081f84256abdcd9e6b5b1cdf56dd/packages/api/src/submittable/createClass.ts#L321
