### ISSUE TITLE
Exception running api.derive.session.info()

### ISSUE THREAD

**Issue by terorie** [polkadot-js/api#3394] opened 2021-04-13 09:53 UTC
**Environment**

- `@polkadot/api 4.5.1`
- Kusama node running `polkadot 0.8.30` 
- Node version `v15.14.0

**Bug description**

Calling `await api.derive.session.info()` throws an exception.

**Example**

Crashing program

```js
const { ApiPromise, WsProvider } = require("@polkadot/api");

async function main() {
  const url = process.env.POLKADOT_RPC || "ws://localhost:9944";
  const wsProvider = new WsProvider(url);
  console.log("Got WsProvider");
  const apiPromise = new ApiPromise({ provider: wsProvider });
  const api = await apiPromise.isReadyOrError;
  console.log("Got API");

  await api.derive.session.info();
}

main()
  .catch((e) => {
    console.error("Fatal error:", e);
    process.exit(1);
  })
  .finally(() => process.exit(0));
```

Console Log

```
$ /snap/bin/node main
Got WsProvider
Got API
2021-04-13 11:52:17             DRR: TypeError: Cannot read property 'creator' of undefined
    at /home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/@polkadot/api/base/Decorate.cjs:330:215
    at Array.map (<anonymous>)
    at Object.queryMulti (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/@polkadot/api/base/Decorate.cjs:330:142)
    at queryStaking (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/@polkadot/api-derive/session/indexes.cjs:29:14)
    at /home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/@polkadot/api-derive/session/indexes.cjs:49:85
    at Observable._subscribe (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/@polkadot/api-derive/util/memo.cjs:23:26)
    at Observable._trySubscribe (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/rxjs/internal/Observable.js:30:22)
    at CatchOperator.call (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/rxjs/internal/operators/catchError.js:30:23)
    at Observable.subscribe (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/rxjs/internal/Observable.js:25:31)
2021-04-13 11:52:17             DRR: TypeError: Cannot read property 'creator' of undefined
    at /home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/@polkadot/api/base/Decorate.cjs:330:215
    at Array.map (<anonymous>)
    at Object.queryMulti (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/@polkadot/api/base/Decorate.cjs:330:142)
    at queryStaking (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/@polkadot/api-derive/session/indexes.cjs:29:14)
    at /home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/@polkadot/api-derive/session/indexes.cjs:49:85
    at Observable._subscribe (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/@polkadot/api-derive/util/memo.cjs:23:26)
    at Observable._trySubscribe (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/rxjs/internal/Observable.js:30:22)
    at CatchOperator.call (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/rxjs/internal/operators/catchError.js:30:23)
    at Observable.subscribe (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/rxjs/internal/Observable.js:25:31)
Fatal error: TypeError: Cannot read property 'creator' of undefined
    at /home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/@polkadot/api/base/Decorate.cjs:330:215
    at Array.map (<anonymous>)
    at Object.queryMulti (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/@polkadot/api/base/Decorate.cjs:330:142)
    at queryStaking (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/@polkadot/api-derive/session/indexes.cjs:29:14)
    at /home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/@polkadot/api-derive/session/indexes.cjs:49:85
    at Observable._subscribe (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/@polkadot/api-derive/util/memo.cjs:23:26)
    at Observable._trySubscribe (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/rxjs/internal/Observable.js:30:22)
    at CatchOperator.call (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/rxjs/internal/operators/catchError.js:30:23)
    at Observable.subscribe (/home/richie/prj/blockdaemon/polkadot-collector-js/node_modules/rxjs/internal/Observable.js:25:31)
```

**Comment by jacogr** [comment] 2021-04-13 10:21
Cannot replicate with either of the following esm/cjs scripts -

```js
// index.mjs
import { ApiPromise, WsProvider } from '@polkadot/api';

async function main () {
  const api = await ApiPromise.create({ provider: new WsProvider('wss://kusama-rpc.polkadot.io') });
  const info = await api.derive.session.info();

  console.log(info);

  process.exit(0);
}

main().catch(() => process.exit(-1));
```

```js
// index.cjs
const { ApiPromise, WsProvider } = require('@polkadot/api');

async function main () {
  const api = await ApiPromise.create({ provider: new WsProvider('wss://kusama-rpc.polkadot.io') });
  const info = await api.derive.session.info();

  console.log(info);

  process.exit(0);
}

main().catch(() => process.exit(-1));
```

**Comment by terorie** [comment] 2021-04-13 11:03
This issue seems to happen only on validator nodes launched very recently. After a while it goes away by itself.

**Comment by jacogr** [comment] 2021-04-13 14:45
So is the node syncing to head when this happens?

**Comment by terorie** [comment] 2021-04-13 15:02
> So is the node syncing to head when this happens?

@jacogr Yes, the node was syncing when this happened. But after the exception disappeared the node was still syncing. I'm not sure what caused it. But it looks like the crash happens on all of our newly launched Kusama nodes.

**Comment by jacogr** [comment] 2021-04-13 15:10
Could be anything for non up-to-date nodes. The issue is the derives detect different paths and it has dropped all support for old code paths which is the reason derives don’t have historic support. 

So basically here you are asking for derive historic support and it adds a lot of overhead and pain in terms of maintenance and speed. 

So the long and the short of it is that the d tubes are only intended for current state queries - which also means the node is in sync.

**Comment by terorie** [comment] 2021-04-14 10:49
@jacogr Oh, I see. When we were ingesting Polkadot blocks in Go we had a lot of these errors on lower blocks as well. That's probably it. If it helps, I can try to reproduce this and capture the JSON-RPC response that crashes `polkadot-js`.

For my use case, I'm only interested in session info for validator monitoring. Only recent blocks count there. I'll change up the program logic to only request those session derive calls when the block height is recent.

Thanks for looking into this :+1:

**Comment by jacogr** [comment] 2021-04-14 11:19
It should be better now while syncing, at least in this case. Made some cleanup which may improve for this specific case. 

The issue is that for older runtimes we didn't have eg. consts (and when there, the babe details were not all exposed, may be a bad example - but basically during upgrades the details do change and on Kusama there has been a lot, including at least 4 versions of the metadata, e.g. how the endpoints into the runtime are described)

So generally the API in the case of derives does the following -

- (obviously any typs as introduced in substrate are added, generaly within the week it gets merged into Substrate master)
- on data changes, the API derives tried to support he previous version as well as the new (in some cases, e.g. account derives, it does support since the beginning of time, but these are the exception)
- once it has made it to Kusama & Polkadot AND Substrate has had a release, the derives will give 2 months leeway for teams to update and then drop support for the old

It is quite difficult to try and navigate all the various incarnations, so while the API can retrieve any historic data, the derives only really supports the current iteration.

**Comment by terorie** [comment] 2021-04-14 12:36
> It is quite difficult to try and navigate all the various incarnations, so while the API can retrieve any historic data, the derives only really supports the current iteration.

Thanks for the explanation. To be honest I didn't read all of the docs yet. But if it's missing maybe your comment is worth adding to the basics page, to prevent misuse? https://polkadot.js.org/docs/api/start/basics

> It should be better now while syncing, at least in this case.

I also just completed a fix on my end, but I'll update this thread in case I find something. The issue is fixed for me for now, so feel free to close.

**Closed** 2021-04-14 13:09 UTC
