### ISSUE TITLE
`ApiPromise` prints an error message when initializing

### ISSUE THREAD

**Issue by carlosala** [polkadot-js/api#5760] opened 2023-11-20 10:20 UTC
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

With the following minimal code, the following gets message gets printed:

```typescript
import { ApiPromise, WsProvider } from "@polkadot/api";

export async function getApi(): Promise<ApiPromise> {
  const url = "wss://rpc.polkadot.io";
  return await ApiPromise.create({ provider: new WsProvider(url) });
}

await getApi()
```

The message `Unable to map [u8; 32] to a lookup index` gets printed.

* **Please tell us about your environment:**

  - Version: `@polkadot/api v10.11.1`
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version) `v5.2.2`
    - [ ] Other

**Comment by xlc** [comment] 2023-11-22 02:44
I think it is caused by https://github.com/polkadot-js/api/pull/5754

**Comment by wottpal** [comment] 2023-11-22 15:33
Hey there, having the same issue and can also confirm that the warning hasn't been there with `10.10.1` (latest release before #5754 got merged).

**Comment by rlaferla** [comment] 2023-12-12 17:41
We are seeing this with `"@polkadot/api": "10.11.1"`

`Unable to map [u8; 32] to a lookup index
`

**Closed** 2023-12-18 07:03 UTC
