### ISSUE TITLE
How to automatically pass the value to custom SignedExtension

### ISSUE THREAD

**Issue by HolyGrease** [polkadot-js/api#5662] opened 2023-05-31 07:01 UTC
- [ ] Bug report
  - [ ] Feature request
  - [X] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

### Current

For now I have custom `SignedExtension` in my substrate node:
```rust
#[derive(Encode, Decode, Clone, Eq, PartialEq, TypeInfo)]
#[scale_info(skip_type_params(T))]
pub struct CheckAccount<T> {
	timestamp: u64,
	_marker: PhantomData<T>,
}
```

In my polkadot-js-api I define this like so:

```js
let signedExtensions = {
    CheckAccount: {
      extrinsic: {
        timestamp: "u64",
      },
      payload: {},
    },
  };
```

```js
const api = await ApiPromise.create({
    ...
    SignedExtensions,
  });
```

And to perform transaction I have specify extension value manually
```js
api.tx.balances
    .transfer(bob, 1000)
    .signAndSend(alice, { timestamp: Date.now() })
```

### Expected

I want to get something like this:

```js
api.setGetterForSignedExtension("CheckAccount", Date.now);
```

And then I just simply can call

```js
api.tx.balances
    .transfer(bob, 1000)
    .signAndSend(Alice);
```

* **Please tell us about your environment:**
macOs Ventura 13.3.1 (m1)

  - Version: `node -v v19.7.0`
  - Environment:

    - [X] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [X] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment] 2024-10-29 01:25
Unfortunately, the addition of the above wont be added as it's out of scope for future work. The issue is appreciated and the idea is nice, but not really something that will be implemented.

Closing for reasons stated above.

**Closed by TarikGul** 2024-10-29 01:25 UTC
