### ISSUE TITLE
KSM Extrinsics error 

### ISSUE THREAD

**Issue by User-8D** [polkadot-js/api#4242] opened 2021-11-20 06:00 UTC
Changing reward address for moonriver contributions. 

Extrinsics/crowdloanRewards/changeAssociationWithRelayKeys(rewardAccount, previousAccount, proofs)

followed instructions provided by Purestake and successfully changed 1 wallet 3 days ago but following the same process during the last 24hrs now has this blocker, even if all the fields are empty, this error persists

multiple browsers on 2 computers and all 4 Moonriver networks have the same error on this page  

Link to page: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss.moonriver.moonbeam.network#/extrinsics

This is the error message:
createType(Call):: Call: failed decoding crowdloanRewards.changeAssociationWithRelayKeys:: Struct: failed on args: {"reward_account":"H160","previous_account":"H160","proofs":"Vec<(AccountId32,SpRuntimeMultiSignature)>"}:: Struct: failed on proofs: Vec<(AccountId32,SpRuntimeMultiSignature)>:: Tuple: failed on 0:: Invalid AccountId provided, expected 32 bytes, found 20

**Comment by jacogr** [comment] 2021-11-20 06:55
As suggested above, the input is incorrect - for the proof it needs a AccountId32, not AccountId20. i.e. it is default Substrate address, not an Ethereum-compatible one.

**Comment by User-8D** [comment] 2021-11-20 07:16
the wallet selection drop down only allows eth style wallets

**Comment by User-8D** [comment] 2021-11-26 06:28
> As suggested above, the input is incorrect - for the proof it needs a AccountId32, not AccountId20. i.e. it is default Substrate address, not an Ethereum-compatible one.

Hey Jacogr, did you try this yourself?

**Comment by jacogr** [comment] 2021-11-26 07:02
This is not API related, I'm assuming it is a duplicate of a apps UI issue, see https://github.com/polkadot-js/apps/issues/6592

**Comment by User-8D** [comment] 2021-11-27 05:14
That does look like it. Thanks Jaco

**Comment by jacogr** [comment] 2021-11-27 10:14
Closing, tracked in apps UI (nothing related to the API layer)

**Closed by jacogr** 2021-11-27 10:14 UTC
Labels: <duplicate>
